name: hep_env
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.4.6
  - jupyterlab-spellchecker=0.7.2
  - matplotlib=3.5.3
  - numpy=1.23.2
  - pandas=1.4.4
  - pip=22.2.2
  - python=3.8.12
  - scipy=1.9.1
  - simpy=4.0.1
  - pip:
    - arrow
    - streamlit==1.17.0
    - plotly==5.13.0
    - fitter
    - seaborn

